-- Combat lockdown, secure actions, macro conditionals, keyboard, menus,
-- pools, combat log.
local FIX = SPEC_DIR .. "/fixtures"

local function newSim(opts)
  opts = opts or {}
  opts.quiet = true
  opts.addonPaths = { FIX }
  return WoW.new(opts)
end

describe("combat lockdown", function()
  it("blocks protected frame changes from addon code in combat", function()
    local sim = newSim()
    sim:Exec('btn = CreateFrame("Button", "MySecureBtn", UIParent, "SecureActionButtonTemplate")')
    local btn = sim:Get("btn")
    sim:EnterCombat()
    sim:Exec("btn:Hide()")
    expect(btn:IsShown()).to_be(true)
    local b = sim:BlockedActions()[1]
    expect(b.kind).to_be("BLOCKED")
    expect(b.action).to_be("MySecureBtn:Hide()")
    expect(sim:EventCount("ADDON_ACTION_BLOCKED")).to_be(1)
    sim:LeaveCombat()
    sim:Exec("btn:Hide()")
    expect(btn:IsShown()).to_be(false)
  end)

  it("still allows changes to normal frames and during PLAYER_REGEN_DISABLED", function()
    local sim = newSim()
    sim:Exec([[
      plain = CreateFrame("Frame", nil, UIParent)
      sec = CreateFrame("Frame", nil, UIParent, "SecureHandlerStateTemplate")
      local w = CreateFrame("Frame")
      w:RegisterEvent("PLAYER_REGEN_DISABLED")
      w:SetScript("OnEvent", function() lockedDuringEvent = InCombatLockdown(); sec:Hide() end)
    ]])
    sim:EnterCombat()
    sim:Exec("plain:Hide()")
    expect(sim:Get("plain"):IsShown()).to_be(false)
    expect(sim:Get("lockedDuringEvent")).to_be(false)
    expect(sim:Get("sec"):IsShown()).to_be(false)
    expect(#sim:BlockedActions()).to_be(0)
    expect(sim:Exec("return InCombatLockdown()")).to_be(true)
  end)

  it("forbids protected functions from addon code", function()
    local sim = newSim()
    sim:Exec('CastSpellByName("Fireball")')
    local b = sim:BlockedActions()[1]
    expect(b.kind).to_be("FORBIDDEN")
    expect(b.action).to_be("CastSpellByName()")
    expect(#sim.secureActions).to_be(0)
  end)

  it("names the addon responsible", function()
    local sim = newSim()
    sim:LoadAddon("NeedsLib")
    local path = FIX .. "/NeedsLib/Evil.lua"
    local f = io.open(path, "w"); f:write("return function() TargetUnit('player') end"); f:close()
    local chunk = assert(loadfile(path))
    setfenv(chunk, sim.env)
    local evil = chunk()
    setfenv(evil, sim.env)
    evil()
    os.remove(path)
    expect(sim:BlockedActions()[1].addon).to_be("NeedsLib")
  end)
end)

describe("secure actions", function()
  local sim
  before_each(function()
    sim = newSim({ spells = { [133] = { name = "Fireball" }, [118] = { name = "Polymorph" } } })
    sim:Exec([[
      b = CreateFrame("Button", "CastBtn", UIParent, "SecureActionButtonTemplate")
      b:SetSize(40, 40); b:SetPoint("CENTER")
      b:SetAttribute("type", "spell")
      b:SetAttribute("spell", "Fireball")
      b:SetAttribute("type2", "macro")
      b:SetAttribute("macrotext2", "/cast [mod:shift] Polymorph; Fireball")
    ]])
  end)

  it("casts when the player clicks, even in combat", function()
    sim:EnterCombat()
    sim:ClickAt("CastBtn")
    expect(sim.secureActions[1].type).to_be("spell")
    expect(sim.secureActions[1].spell).to_be("Fireball")
  end)

  it("resolves macro conditionals with modifier keys", function()
    sim:Get("b"):RegisterForClicks("AnyUp")
    sim:ClickAt("CastBtn", "RightButton")
    expect(sim.secureActions[1].casts[1].spell).to_be("Fireball")
    sim:SetModifier("shift", true)
    sim:ClickAt("CastBtn", "RightButton")
    expect(sim.secureActions[2].casts[1].spell).to_be("Polymorph")
  end)

  it("refuses button:Click() from addon code", function()
    sim:Exec("b:Click()")
    expect(#sim.secureActions).to_be(0)
    expect(sim:BlockedActions()[1].kind).to_be("FORBIDDEN")
  end)

  it("works through CLICK key bindings", function()
    sim:SetBinding("1", "CLICK CastBtn:LeftButton")
    sim:PressKey("1")
    expect(sim.secureActions[1].spell).to_be("Fireball")
  end)
end)

describe("macro conditionals and state drivers", function()
  it("parses SecureCmdOptionParse like the client", function()
    local sim = newSim()
    expect(sim:Exec('return SecureCmdOptionParse("[combat] a; b")')).to_be(true)
    local _, v = sim:Exec('return SecureCmdOptionParse("[combat] a; b")')
    expect(v).to_be("b")
    sim:EnterCombat()
    _, v = sim:Exec('return SecureCmdOptionParse("[combat] a; b")')
    expect(v).to_be("a")
    sim:SetTarget({ name = "Boar", hostile = true })
    local _, v2, u = sim:Exec('return SecureCmdOptionParse("[@focus,exists] x; [harm,nodead] y; z")')
    expect({ v2, u }).to_equal({ "y", nil })
    local _, v3, u3 = sim:Exec('return SecureCmdOptionParse("[@target,harm] Fireball")')
    expect({ v3, u3 }).to_equal({ "Fireball", "target" })
  end)

  it("drives visibility from RegisterStateDriver, even in combat", function()
    local sim = newSim()
    sim:Exec([[
      bar = CreateFrame("Frame", nil, UIParent, "SecureHandlerStateTemplate")
      RegisterStateDriver(bar, "visibility", "[combat] show; hide")
    ]])
    local bar = sim:Get("bar")
    expect(bar:IsShown()).to_be(false)
    sim:EnterCombat()
    expect(bar:IsShown()).to_be(true)
    sim:LeaveCombat()
    expect(bar:IsShown()).to_be(false)
    expect(#sim:BlockedActions()).to_be(0)
  end)

  it("runs _onstate snippets in the restricted environment", function()
    local sim = newSim()
    sim:Exec([[
      h = CreateFrame("Frame", nil, UIParent, "SecureHandlerStateTemplate")
      child = CreateFrame("Frame", "StateChild", h)
      h:SetFrameRef("child", child)
      h:SetAttribute("_onstate-mod", [=[
        local c = self:GetFrameRef("child")
        if newstate == "shift" then c:Hide() else c:Show() end
        self:SetAttribute("last", newstate)
      ]=])
      RegisterStateDriver(h, "mod", "[mod:shift] shift; none")
    ]])
    sim:SetModifier("shift", true)
    expect(sim:Get("StateChild"):IsShown()).to_be(false)
    expect(sim:Get("h"):GetAttribute("last")).to_be("shift")
    sim:SetModifier("shift", false)
    expect(sim:Get("StateChild"):IsShown()).to_be(true)
  end)
end)

describe("keyboard", function()
  it("types into the focused edit box and handles special keys", function()
    local sim = newSim()
    sim:Exec([[
      eb = CreateFrame("EditBox", nil, UIParent)
      eb:SetScript("OnEnterPressed", function(self) sent = self:GetText(); self:ClearFocus() end)
      eb:SetFocus()
    ]])
    sim:TypeText("Hi there")
    sim:PressKey("BACKSPACE")
    sim:PressKey("ENTER")
    expect(sim:Get("sent")).to_be("Hi ther")
    expect(sim:Get("eb"):HasFocus()).to_be(false)
  end)

  it("gives keyboard-enabled frames first pick, with propagation", function()
    local sim = newSim()
    sim:Exec([[
      k = CreateFrame("Frame", nil, UIParent); k:SetSize(10, 10); k:SetPoint("CENTER")
      k:EnableKeyboard(true)
      k:SetScript("OnKeyDown", function(_, key) lastKey = key end)
    ]])
    sim:SetBinding("F", "XMLADDON_TOGGLE")
    sim:PressKey("SHIFT-F")
    expect(sim:Get("lastKey")).to_be("SHIFT-F")
    sim:Exec("k:SetPropagateKeyboardInput(true)")
    sim:PressKey("CTRL-F")
    expect(sim:Get("lastKey")).to_be("CTRL-F")
  end)

  it("closes UISpecialFrames on ESCAPE", function()
    local sim = newSim()
    sim:Exec('win = CreateFrame("Frame", "MyWindow", UIParent); tinsert(UISpecialFrames, "MyWindow")')
    sim:PressKey("ESCAPE")
    expect(sim:Get("win"):IsShown()).to_be(false)
  end)

  it("supports SetBinding/GetBindingKey and override bindings", function()
    local sim = newSim()
    local _, key = sim:Exec('SetBinding("ctrl-shift-x", "TOGGLEBAG1"); return GetBindingKey("TOGGLEBAG1")')
    expect(key).to_be("CTRL-SHIFT-X")
    sim:Exec([[
      ob = CreateFrame("Button", "OverBtn", UIParent)
      ob:SetScript("OnClick", function() overClicked = true end)
      SetOverrideBindingClick(ob, true, "CTRL-SHIFT-X", "OverBtn")
    ]])
    sim:PressKey("CTRL-SHIFT-X")
    expect(sim:Get("overClicked")).to_be(true)
    sim:EnterCombat()
    sim:Exec('SetBinding("Z", "JUMP")')
    expect(sim:BlockedActions()[1].action).to_be("SetBinding()")
  end)
end)

describe("FrameXML utilities", function()
  it("provides frame pools", function()
    local sim = newSim()
    local _, a, active, reused = sim:Exec([[
      local pool = CreateFramePool("Button", UIParent, "UIPanelButtonTemplate")
      local b1 = pool:Acquire(); local b2 = pool:Acquire()
      pool:Release(b1)
      local b3, isNew = pool:Acquire()
      return b1.Text ~= nil, pool:GetNumActive(), b3 == b1 and not isNew
    ]])
    expect({ a, active, reused }).to_equal({ true, 2, true })
  end)

  it("provides CallbackRegistryMixin", function()
    local sim = newSim()
    local _, got = sim:Exec([[
      local reg = CreateFromMixins(CallbackRegistryMixin)
      reg:OnLoad()
      reg:GenerateCallbackEvents({ "Changed" })
      local owner = {}
      reg:RegisterCallback("Changed", function(o, v) seen = v end, owner)
      reg:TriggerEvent("Changed", 42)
      return seen
    ]])
    expect(got).to_be(42)
  end)

  it("formats time like the client", function()
    local sim = newSim()
    local _, a, b, c = sim:Exec('return SecondsToTime(3725), SecondsToClock(3725), SecondsToTime(90, false, true)')
    expect({ a, b, c }).to_equal({ "1 Hr 2 Min", "1:02:05", "1 Minute 30 Seconds" })
  end)

  it("drives MenuUtil context menus and dropdowns", function()
    local sim = newSim()
    sim:Exec([[
      choice = "b"
      dd = CreateFrame("DropdownButton", nil, UIParent, "WowStyle1DropdownTemplate")
      dd:SetPoint("TOPLEFT", 100, -100)
      dd:SetupMenu(function(owner, root)
        root:CreateTitle("Pick one")
        for _, v in ipairs({ "a", "b", "c" }) do
          root:CreateRadio(v:upper(), function() return choice == v end, function() choice = v end)
        end
      end)
    ]])
    local dd = sim:Get("dd")
    expect(dd:GetText()).to_be("B")
    sim:ClickAt(dd)
    expect(sim.openMenu).never.to_be_nil()
    local items = sim:MenuItems()
    expect(items[1].text).to_be("Pick one")
    expect(items[3].selected).to_be(true)
    sim:ChooseMenuItem("C")
    expect(sim:Get("choice")).to_be("c")
    expect(dd:GetText()).to_be("C")
  end)

  it("loads Item data through ContinueOnItemLoad", function()
    local sim = newSim({ items = { [6948] = { name = "Hearthstone" } } })
    sim:Exec('Item:CreateFromItemID(6948):ContinueOnItemLoad(function() itemName = "ok" end)')
    expect(sim:Get("itemName")).to_be("ok")
  end)
end)

describe("combat log", function()
  it("fires COMBAT_LOG_EVENT_UNFILTERED with the client's argument layout", function()
    local sim = newSim({ spells = { [133] = { name = "Fireball" } } })
    sim:SetTarget({ name = "Hogger", hostile = true, guid = "Creature-0-1-2-3-448-0001" })
    sim:Exec([[
      local f = CreateFrame("Frame")
      f:RegisterEvent("COMBAT_LOG_EVENT_UNFILTERED")
      f:SetScript("OnEvent", function()
        local _, sub, _, src, srcName, _, _, dst, dstName, _, _, spellId, spellName, school, amount, _, _, _, _, _, crit = CombatLogGetCurrentEventInfo()
        logged = { sub, srcName, dstName, spellId, spellName, amount, crit }
      end)
    ]])
    sim:CombatLog("SPELL_DAMAGE", { source = "player", dest = "target", spellId = 133, amount = 1234, critical = true, school = 4 })
    expect(sim:Get("logged")).to_equal({ "SPELL_DAMAGE", "Tester", "Hogger", 133, "Fireball", 1234, true })
  end)
end)

describe("secret values (opt-in)", function()
  it("makes flagged API returns secret in combat, usable by widgets only", function()
    local sim = newSim({ secretValues = true })
    sim:SetTarget({ name = "Boss", hostile = true, health = 900, healthMax = 1000 })
    sim:Exec('bar = CreateFrame("StatusBar", nil, UIParent)')
    local _, before = sim:Exec('return UnitHealth("target")')
    expect(before).to_be(900)
    sim:EnterCombat()
    -- UnitHealth is documented SecretReturns (player included); UnitPower is
    -- SecretWhenUnitPowerRestricted, which exempts the player
    local _, isSecret, typ, mine, myPower = sim:Exec([[
      local h = UnitHealth("target")
      return issecretvalue(h), type(h), issecretvalue(UnitHealth("player")), issecretvalue(UnitPower("player"))
    ]])
    expect({ isSecret, typ, mine, myPower }).to_equal({ true, "number", true, false })
    local ok, err = sim:Exec('return UnitHealth("target") + 1')
    expect(ok).to_be(false)
    expect(err).to_match("secret value")
    sim:ClearErrors()
    sim:Exec('bar:SetMinMaxValues(0, UnitHealthMax("target")); bar:SetValue(UnitHealth("target"))')
    expect(sim:Get("bar"):GetValue()).to_be(900)
    local _, scrubbed = sim:Exec('return scrubsecretvalues(UnitHealth("target"))')
    expect(scrubbed).to_be_nil()
    sim:LeaveCombat()
    local _, after = sim:Exec('return issecretvalue(UnitHealth("target"))')
    expect(after).to_be(false)
  end)

  it("is off by default", function()
    local sim = newSim()
    sim:EnterCombat()
    local _, s = sim:Exec('return issecretvalue(UnitHealth("target"))')
    expect(s).to_be(false)
  end)
end)
