-- UI simulation: XML frames, layout, mouse input, animations, screenshots.
local FIX = SPEC_DIR .. "/fixtures"

local function newSim(opts)
  opts = opts or {}
  opts.quiet = true
  opts.addonPaths = { FIX }
  return WoW.new(opts)
end

describe("XML", function()
  local sim, f
  before_each(function()
    sim = newSim()
    assert(sim:LoadAddon("XmlAddon"))
    sim:Login()
    f = sim:Get("XmlAddonFrame")
  end)

  it("runs <Script> files with the addon's name and namespace", function()
    expect(sim:Get("XmlAddonRan")).to_be("XmlAddon")
  end)

  it("builds frames, layers, keys, arrays and KeyValues", function()
    expect(f:GetObjectType()).to_be("Frame")
    expect(f.Title:GetText()).to_be("From XML")
    expect(f.Bg:GetObjectType()).to_be("Texture")
    expect(#f.Rows).to_be(2)
    expect(f.Rows[1]:GetName()).to_be("XmlAddonFrameRow1")
    expect(f.Rows[2]:GetID()).to_be(2)
    expect(f.maxRows).to_be(2)
    expect(f.Close:GetParent()).to_be(f)
  end)

  it("applies mixins and runs child OnLoad before the parent's", function()
    expect(sim:Get("XmlAddonLoadOrder")).to_equal({ "XmlAddonFrameRow1", "XmlAddonFrameRow2", "XmlAddonFrame" })
    expect(f.gotLogin).to_be(true)
  end)

  it("resolves anchors, including relativeKey and $parent names", function()
    local l, b, w, h = f:GetRect()
    expect({ l, b, w, h }).to_equal({ 870, 460, 200, 120 })
    local _, rel = f.Rows[1]:GetPoint()
    expect(rel).to_be(f.Title)
    expect(f.Rows[2]:GetTop()).to_be(f.Rows[1]:GetBottom())
    expect(f.Bg:GetWidth()).to_be(200)
  end)

  it("uses <Font> objects", function()
    local _, size = f.Title:GetFont()
    expect(size).to_be(18)
    local r, g, b = f.Title:GetTextColor()
    expect({ r, g, b }).to_equal({ 0.2, 0.8, 1 })
  end)

  it("wires method= and inline scripts", function()
    sim:Click(f.Rows[2])
    expect(sim:Get("XmlAddonClicked")).to_be(2)
    sim:Click(f.Close)
    expect(f:IsShown()).to_be(false)
  end)

  it("plays XML animations", function()
    f:Hide()
    f:Show()
    sim:Advance(0.25)
    expect(f:GetAlpha()).to_be_close_to(0.5)
    sim:Advance(0.5)
    expect(sim:Get("XmlAddonFaded")).to_be(true)
    expect(f:GetAlpha()).to_be(1)
  end)

  it("makes virtual templates available to CreateFrame", function()
    local _, row = sim:Exec('return CreateFrame("Button", "DynRow", UIParent, "XmlRowTemplate")')
    expect(row.Label:GetObjectType()).to_be("FontString")
    expect(row:GetWidth()).to_be(180)
    expect(sim:Get("XmlAddonLoadOrder")[4]).to_be("DynRow")
  end)

  it("errors on unknown templates", function()
    local ok, err = sim:Exec('CreateFrame("Frame", nil, UIParent, "NoSuchTemplate")')
    expect(ok).to_be(false)
    expect(err).to_match('Couldn\'t find inherited node "NoSuchTemplate"')
    sim:ClearErrors()
  end)

  it("loads Bindings.xml and runs bindings on key press", function()
    sim:SetBinding("CTRL-T", "XMLADDON_TOGGLE")
    sim:PressKey("CTRL-T")
    expect(f:IsShown()).to_be(false)
    sim:PressKey("CTRL-T")
    expect(f:IsShown()).to_be(true)
  end)

  it("parses tricky XML", function()
    local root = require("wowapi.xml").parse([==[<?xml version="1.0"?>
<Ui><!-- c --><Script><![CDATA[x = 1 < 2]]></Script><Frame name="A&amp;B" hidden='true'/></Ui>]==], "t.xml")
    local ui = root.children[1]
    expect(ui.children[1].text).to_be("x = 1 < 2")
    expect(ui.children[2].attrs.name).to_be("A&B")
    expect(ui.children[2].attrs.hidden).to_be("true")
    expect(function() require("wowapi.xml").parse("<Ui><Frame></Ui>", "bad.xml") end).to_error("bad.xml:1: XML error")
  end)
end)

describe("layout", function()
  it("resolves points, sizes and scale to screen coordinates", function()
    local sim = newSim()
    local _, l, b, w, h = sim:Exec([[
      local p = CreateFrame("Frame", nil, UIParent); p:SetSize(200, 100); p:SetPoint("BOTTOMLEFT", 100, 50)
      local c = CreateFrame("Frame", nil, p); c:SetPoint("TOPLEFT", 10, -10); c:SetPoint("BOTTOMRIGHT", -10, 10)
      return c:GetRect()
    ]])
    expect({ l, b, w, h }).to_equal({ 110, 60, 180, 80 })
    local _, sl, ss = sim:Exec([[
      local f = CreateFrame("Frame", nil, UIParent); f:SetScale(2); f:SetSize(10, 10); f:SetPoint("BOTTOMLEFT", 100, 0)
      return f:GetLeft(), f:GetEffectiveScale()
    ]])
    expect({ sl, ss }).to_equal({ 100, 2 })
  end)

  it("returns nil positions for unanchored frames", function()
    local sim = newSim()
    local _, left = sim:Exec('local f = CreateFrame("Frame"); f:SetSize(5, 5); return f:GetLeft()')
    expect(left).to_be_nil()
  end)

  it("sizes FontStrings from their text", function()
    local sim = newSim()
    local _, short, long = sim:Exec([[
      local f = UIParent:CreateFontString(nil, "OVERLAY", "GameFontNormal")
      f:SetText("hi"); local a = f:GetStringWidth()
      f:SetText("a much longer line"); return a, f:GetStringWidth()
    ]])
    expect(long).to_be_greater_than(short)
  end)

  it("rejects bad points and anchor loops like the client", function()
    local sim = newSim()
    expect(sim:Exec('CreateFrame("Frame"):SetPoint("MIDDLE")')).to_be(false)
    local ok, err = sim:Exec([[
      local a = CreateFrame("Frame", nil, UIParent); local b = CreateFrame("Frame", nil, UIParent)
      a:SetPoint("TOP", b, "BOTTOM"); b:SetPoint("TOP", a, "BOTTOM")
    ]])
    expect(ok).to_be(false)
    expect(err).to_match("dependent on it")
    sim:ClearErrors()
  end)

  it("requires BackdropTemplate for SetBackdrop", function()
    local sim = newSim()
    expect(sim:Exec('CreateFrame("Frame"):SetBackdrop({})')).to_be(false)
    sim:ClearErrors()
    expect(sim:Exec('CreateFrame("Frame", nil, nil, "BackdropTemplate"):SetBackdrop({})')).to_be(true)
  end)
end)

describe("mouse", function()
  local sim
  before_each(function()
    sim = newSim()
    sim:Exec([[
      log = {}
      back = CreateFrame("Button", "Back", UIParent); back:SetSize(100, 100); back:SetPoint("CENTER")
      front = CreateFrame("Button", "Front", UIParent); front:SetSize(40, 40); front:SetPoint("CENTER"); front:SetFrameStrata("HIGH")
      for _, b in ipairs({ back, front }) do
        b:SetScript("OnEnter", function(self) tinsert(log, "enter " .. self:GetName()) end)
        b:SetScript("OnLeave", function(self) tinsert(log, "leave " .. self:GetName()) end)
        b:SetScript("OnClick", function(self, btn) tinsert(log, "click " .. self:GetName() .. " " .. btn) end)
      end
    ]])
  end)

  it("hit-tests by strata and fires enter/leave", function()
    sim:MoveMouse(960, 540)
    sim:MoveMouse(920, 540)
    sim:MoveMouse(0, 0)
    expect(sim:Get("log")).to_equal({ "enter Front", "leave Front", "enter Back", "leave Back" })
  end)

  it("clicks whatever is on top, honouring RegisterForClicks", function()
    sim:ClickAt(960, 540)
    sim:ClickAt(920, 540, "RightButton")
    sim:Get("back"):RegisterForClicks("AnyUp")
    sim:ClickAt(920, 540, "RightButton")
    local log = sim:Get("log")
    expect(log).to_contain("click Front LeftButton")
    expect(log).never.to_contain("click Back LeftButton")
    local rights = 0
    for _, l in ipairs(log) do if l == "click Back RightButton" then rights = rights + 1 end end
    expect(rights).to_be(1)
  end)

  it("drags movable frames and re-anchors them", function()
    sim:Exec([[
      back:SetMovable(true); back:RegisterForDrag("LeftButton")
      back:SetScript("OnDragStart", back.StartMoving)
      back:SetScript("OnDragStop", back.StopMovingOrSizing)
    ]])
    sim:Drag("Back", 50, 20)
    local b = sim:Get("back")
    expect({ b:GetLeft(), b:GetTop() }).to_equal({ 960, 610 })
    expect(b:GetPoint()).to_be("TOPLEFT")
    expect(b:IsUserPlaced()).to_be(true)
  end)

  it("delivers mouse wheel only when enabled", function()
    sim:Exec('back:SetScript("OnMouseWheel", function(_, d) wheel = d end)')
    expect(sim:Scroll("Back", -1)).to_be(false)
    sim:Exec("back:EnableMouseWheel(true)")
    sim:Scroll("Back", -1)
    expect(sim:Get("wheel")).to_be(-1)
  end)
end)

describe("animations", function()
  it("sequences by order, loops, and reverts unless SetToFinalAlpha", function()
    local sim = newSim()
    sim:Exec([[
      f = CreateFrame("Frame", nil, UIParent); f:SetSize(10, 10); f:SetPoint("BOTTOMLEFT")
      g = f:CreateAnimationGroup()
      local a = g:CreateAnimation("Alpha"); a:SetFromAlpha(1); a:SetToAlpha(0); a:SetDuration(1)
      local t = g:CreateAnimation("Translation"); t:SetOffset(100, 0); t:SetDuration(1); t:SetOrder(2)
      loops = 0
      g:SetScript("OnLoop", function() loops = loops + 1 end)
    ]])
    local f, g = sim:Get("f"), sim:Get("g")
    g:Play()
    sim:Advance(0.5)
    expect(f:GetAlpha()).to_be_close_to(0.5)
    sim:Advance(1)
    expect(f:GetLeft()).to_be_close_to(50)
    sim:Advance(1)
    expect(g:IsPlaying()).to_be(false)
    expect({ f:GetAlpha(), f:GetLeft() }).to_equal({ 1, 0 })
    g:SetLooping("REPEAT")
    g:Play()
    sim:Advance(4.5)
    expect(sim:Get("loops")).to_be(2)
    g:Stop()
    expect(f:GetAlpha()).to_be(1)
  end)
end)

describe("screenshots", function()
  it("renders visible frames and text to SVG", function()
    local sim = newSim()
    sim:LoadAddon("XmlAddon")
    sim:Login()
    local svg = sim:Screenshot(nil, { outlines = true })
    expect(svg).to_match("^<svg")
    expect(svg).to_contain("From XML")
    expect(svg).to_contain("XmlAddonFrame")
    sim:Get("XmlAddonFrame"):Hide()
    expect(sim:Screenshot()).never.to_contain("From XML")
  end)
end)
