-- Fake game data and game art resolution.
local function newSim(opts)
  opts = opts or {}
  opts.quiet = true
  return WoW.new(opts)
end

describe("fake game data", function()
  it("turns item IDs into complete, stable items", function()
    local sim = newSim()
    local _, name, link, quality, ilvl, _, itype, _, _, equipLoc, icon = sim:Exec("return C_Item.GetItemInfo(123459)")
    expect(name).to_be_type("string")
    expect(link).to_match("|Hitem:123459:")
    expect(quality).to_be_type("number")
    expect(ilvl).to_be_greater_than(0)
    expect(icon).to_be_greater_than(0)
    local _, again = sim:Exec("return C_Item.GetItemInfo(123459)")
    expect(again).to_be(name)
    local _, other = newSim():Exec("return C_Item.GetItemInfo(123459)")
    expect(other).to_be(name) -- same on every run
    -- like the real (sparse) ID space, most IDs are not items
    local _, none = sim:Exec("return C_Item.GetItemInfo(123456)")
    expect(none).to_be_nil()
  end)

  it("knows real items and spells", function()
    local sim = newSim()
    local _, hs = sim:Exec("return C_Item.GetItemInfo(6948)")
    expect(hs).to_be("Hearthstone")
    local _, fb = sim:Exec("return C_Spell.GetSpellInfo(133)")
    expect(fb.name).to_be("Fireball")
    local _, byName = sim:Exec('return C_Spell.GetSpellInfo("Frostbolt")')
    expect(byName.spellID).to_be(116)
  end)

  it("generates spells for existing IDs", function()
    local sim = newSim()
    local _, info = sim:Exec("return C_Spell.GetSpellInfo(424244)")
    expect(info.name).to_match("%a+ %a+")
    expect(info.iconID).to_be_greater_than(0)
  end)

  it("gives the player real class data", function()
    local sim = newSim({ player = { class = "MAGE" } })
    local _, ptype, token = sim:Exec('return UnitPowerType("player")')
    expect({ ptype, token }).to_equal({ 0, "MANA" })
    local _, id, name, _, _, role = sim:Exec("return GetSpecializationInfo(2)")
    expect({ id, name, role }).to_equal({ 63, "Fire", "DAMAGER" })
    expect(sim:Exec("return IsPlayerSpell(133)")).to_be(true)
    local _, known = sim:Exec("return IsPlayerSpell(133)")
    expect(known).to_be(true)
    local _, notMine = sim:Exec("return IsPlayerSpell(2061)")
    expect(notMine).to_be(false)
  end)

  it("fills bags", function()
    local sim = newSim()
    local _, slots, first = sim:Exec("return C_Container.GetContainerNumSlots(0), C_Container.GetContainerItemInfo(0, 1)")
    expect(slots).to_be(16)
    expect(first.itemName).to_be("Hearthstone")
    local _, count = sim:Exec("return C_Item.GetItemCount(6948)")
    expect(count).to_be(1)
  end)

  it("spawns parties, raids and enemies", function()
    local sim = newSim()
    sim:SpawnParty(4)
    local _, n, name, cls = sim:Exec('return GetNumGroupMembers(), UnitName("party2"), select(2, UnitClass("party2"))')
    expect(n).to_be(5)
    expect(name).to_be_type("string")
    expect(cls).to_be_type("string")
    sim:SpawnRaid(20)
    local _, rn, rname, _, sub = sim:Exec("return GetNumGroupMembers(), GetRaidRosterInfo(7)")
    expect(rn).to_be(20)
    expect(sub).to_be(2)
    local boss = sim:SpawnEnemy({ boss = true })
    local _, tname, cls2 = sim:Exec('return UnitName("target"), UnitClassification("boss1")')
    expect(tname).to_be(boss.name)
    expect(cls2).to_be("worldboss")
  end)

  it("applies auras and casts spells with events and cooldowns", function()
    local sim = newSim({ player = { class = "MAGE" } })
    sim:Exec([[
      events = {}
      local f = CreateFrame("Frame")
      for _, e in ipairs({ "UNIT_AURA", "UNIT_SPELLCAST_START", "UNIT_SPELLCAST_SUCCEEDED", "SPELL_UPDATE_COOLDOWN" }) do f:RegisterEvent(e) end
      f:SetScript("OnEvent", function(_, e) tinsert(events, e) end)
    ]])
    sim:AddAura("player", 1459, { duration = 3600 })
    local _, aura = sim:Exec("return C_UnitAuras.GetPlayerAuraBySpellID(1459)")
    expect(aura.name).to_be("Arcane Intellect")
    sim:SpawnEnemy()
    sim:Cast(133)
    sim:Cast("Blink")
    local _, cd = sim:Exec("return C_Spell.GetSpellCooldown(1953)")
    expect(cd.duration).to_be(15)
    expect(sim:Get("events")).to_equal({ "UNIT_AURA", "UNIT_SPELLCAST_START", "UNIT_SPELLCAST_SUCCEEDED",
      "UNIT_SPELLCAST_SUCCEEDED", "SPELL_UPDATE_COOLDOWN" })
  end)

  it("returns plausible data from every other documented function", function()
    local sim = newSim()
    local _, mapInfo, currency, n = sim:Exec("return C_Map.GetMapInfo(84), C_CurrencyInfo.GetCurrencyInfo(1792), C_CurrencyInfo.GetCurrencyListSize()")
    expect(mapInfo.name).to_be_type("string")
    expect(currency.name).to_be_type("string")
    expect(currency.quantity).to_be_type("number")
    expect(n).to_be_type("number")
    -- deterministic
    local _, again = sim:Exec("return C_CurrencyInfo.GetCurrencyInfo(1792)")
    expect(again.name).to_be(currency.name)
  end)

  it("can be switched off", function()
    local sim = newSim({ fakeData = false })
    local _, item = sim:Exec("return C_Item.GetItemInfo(123456)")
    expect(item).to_be_nil()
  end)
end)

describe("game art", function()
  it("knows real atlases and their sizes", function()
    local sim = newSim()
    local _, info = sim:Exec('return C_Texture.GetAtlasInfo("RedButton-Exit")')
    expect({ info.width, info.height }).to_equal({ 18, 19 })
    local _, ok, w = sim:Exec('local t = UIParent:CreateTexture(); local ok = t:SetAtlas("RedButton-Exit", true); return ok, t:GetWidth()')
    expect({ ok, w }).to_equal({ true, 18 })
    local _, bad = sim:Exec('return UIParent:CreateTexture():SetAtlas("NoSuchAtlas")')
    expect(bad).to_be(false)
  end)

  it("maps icon fileIDs to icon names offline", function()
    local A = require("wowapi.assets")
    local byId = A.icons()
    expect(byId[135812]).to_be("spell_fire_flamebolt")
    local store = A.store({ offline = true, cacheDir = os.tmpname() .. "_c" })
    expect(store:pathFor(135812)).to_be("icons/spell_fire_flamebolt")
    expect(store:pathFor("Interface\\Buttons\\UI-Panel-Button-Up.blp")).to_be("buttons/ui-panel-button-up")
  end)

  it("uses a local art folder and embeds real images in screenshots", function()
    local dir = os.tmpname() .. "_art"
    os.execute('mkdir -p "' .. dir .. '/ICONS"')
    -- a 1x1 red PNG
    local png = require("wowapi.png").encode(1, 1, "\255\0\0\255")
    local f = io.open(dir .. "/ICONS/Spell_Fire_FlameBolt.PNG", "wb"); f:write(png); f:close()
    local sim = newSim({ art = true, artDir = dir, offline = true, artCache = dir .. "/cache" })
    sim:Exec('local t = UIParent:CreateTexture(); t:SetSize(64, 64); t:SetPoint("CENTER"); t:SetTexture(135812)')
    local svg = sim:Screenshot()
    expect(svg).to_contain("data:image/png;base64,")
    os.execute('rm -rf "' .. dir .. '"')
  end)

  it("decodes BLP textures", function()
    -- 4x4 DXT1 block, solid colour 0xF800 (pure red), all indices 0
    local header = "BLP2" .. "\1\0\0\0" .. "\2\0\0\0" .. "\4\0\0\0" .. "\4\0\0\0"
    local offsets = string.char(0x94, 0x04, 0, 0) .. string.rep("\0", 60)
    local sizes = string.char(8, 0, 0, 0) .. string.rep("\0", 60)
    local blp = header .. offsets .. sizes .. string.rep("\0", 1024) .. string.char(0x00, 0xF8, 0x00, 0x00, 0, 0, 0, 0)
    local w, h, rgba = require("wowapi.blp").decode(blp)
    expect({ w, h }).to_equal({ 4, 4 })
    expect({ rgba:byte(1, 4) }).to_equal({ 255, 0, 0, 255 })
  end)
end)
