-- Run with: ./wowtest test addons/HelloForever
describe("HelloForever", function()
  local sim

  before_each(function()
    -- Boot() = new simulated client + load this addon + log in
    sim = Boot({ player = { name = "Thrall", class = "SHAMAN", level = 60 } })
  end)

  describe("login", function()
    it("greets the player by name", function()
      expect(sim:ChatContains("Hello, Thrall!", true)).to_be(true)
    end)

    it("counts logins per character across reloads", function()
      expect(sim:Get("HelloForeverCharDB").logins).to_be(1)
      sim:Slash("/reload")
      sim:Slash("/reload")
      expect(sim:Get("HelloForeverCharDB").logins).to_be(3)
    end)

    it("does not greet when greeting is turned off", function()
      sim:Slash("/hf greet off")
      sim:ClearChat()
      sim:Reload()
      expect(sim:ChatContains("Hello", true)).to_be(false)
    end)

    it("uses the German greeting on a deDE client", function()
      local de = Boot({ locale = "deDE", player = { name = "Thrall" } })
      expect(de:ChatContains("Hallo, Thrall!", true)).to_be(true)
    end)

    it("doesn't leak globals", function()
      expect(sim:LeakedGlobals("HelloForever")).to_equal({})
    end)
  end)

  describe("slash commands", function()
    it("works with both aliases", function()
      sim:Slash("/hf count")
      expect(sim:LastChat()).to_match("logged in 1 time")
      sim:Slash("/HELLOFOREVER count")
      expect(sim:LastChat()).to_match("logged in 1 time")
    end)

    it("prints usage for unknown input", function()
      sim:Slash("/hf wat")
      expect(sim:LastChat()).to_match("^Usage:")
    end)

    it("hides and shows the window and remembers it", function()
      local frame = sim:Get("HelloForeverFrame")
      expect(frame:IsShown()).to_be(true)
      sim:Slash("/hf hide")
      expect(frame:IsShown()).to_be(false)
      sim:Reload()
      expect(sim:Get("HelloForeverFrame"):IsShown()).to_be(false)
    end)
  end)

  describe("timers", function()
    it("fires a reminder after the delay, not before", function()
      sim:Slash("/hf remind 10 drink water")
      sim:Advance(9.9)
      expect(sim:ChatContains("Reminder", true)).to_be(false)
      sim:Advance(0.1)
      expect(sim:LastChat()).to_be("Reminder: drink water")
      expect(sim.sounds[1].id).to_be(sim:Get("SOUNDKIT").RAID_WARNING)
    end)

    it("updates the session timer from OnUpdate", function()
      sim:Advance(3)
      expect(sim:Get("HelloForeverFrame").timer:GetText()).to_be("Session: 3s")
    end)
  end)

  describe("combat", function()
    it("reports combat duration", function()
      sim:EnterCombat()
      sim:Advance(4.5)
      sim:LeaveCombat()
      expect(sim:LastChat()).to_be("Combat lasted 4.5 seconds.")
    end)
  end)

  describe("UI", function()
    it("tracks player health on UNIT_HEALTH", function()
      local bar = sim:Get("HelloForeverFrame").health
      expect(bar:GetValue()).to_be(5000)
      sim.player.health = 1200
      sim:FireEvent("UNIT_HEALTH", "player")
      expect(bar:GetValue()).to_be(1200)
      -- events for other units are filtered by RegisterUnitEvent
      sim.player.health = 1
      sim:FireEvent("UNIT_HEALTH", "target")
      expect(bar:GetValue()).to_be(1200)
    end)

    it("emotes when the Wave button is clicked", function()
      sim:Click("HelloForeverWaveButton")
      expect(sim.sentChat[1]).to_equal({ msg = "waves hello from WoW: Forever!", chatType = "EMOTE" })
    end)

    it("can be dragged around the screen", function()
      local frame = sim:Get("HelloForeverFrame")
      local left, top = frame:GetLeft(), frame:GetTop()
      sim:Drag(frame, 150, -40)
      expect(frame:GetLeft()).to_be(left + 150)
      expect(frame:GetTop()).to_be(top - 40)
    end)

    it("renders", function()
      local svg = sim:Screenshot()
      expect(svg).to_contain("Hello Forever")
      expect(svg).to_contain("Wave")
    end)

    it("shows a tooltip on hover", function()
      local button = sim:Get("HelloForeverWaveButton")
      sim:Hover(button)
      local tip = sim:Get("GameTooltip")
      expect(tip:IsShown()).to_be(true)
      expect(tip:GetLines()[2].left).to_be("Sends a friendly emote.")
      sim:Leave(button)
      expect(tip:IsShown()).to_be(false)
    end)
  end)
end)
