-- Generates wowapi/data/resources.lua from Ketho's BlizzardInterfaceResources
-- (https://github.com/Ketho/BlizzardInterfaceResources, Resources/ folder):
-- global API names, FrameXML functions, named frames, templates, CVars,
-- Lua enums/constants and events of the live client.
--
--   lua5.1 tools/gen-resources.lua <Resources dir> "<source>" > wowapi/data/resources.lua
local dir, source = arg[1], arg[2] or "unknown"
assert(dir, "usage: gen-resources.lua <Resources dir> [source]")

local function load(name, env)
  local chunk = assert(loadfile(dir .. "/" .. name))
  setfenv(chunk, env or {})
  return chunk()
end

local GlobalAPI, LuaAPI = unpack(load("GlobalAPI.lua"))
local FrameXML = unpack(load("FrameXML.lua"))
local Frames = unpack(load("Frames.lua"))
local Templates = load("Templates.lua")
local Mixins = load("Mixins.lua")
local Events = load("Events.lua")
local CVars = unpack(load("CVars.lua"))
local enumEnv = {}
load("LuaEnum.lua", enumEnv)

local out = { source = source }
table.sort(GlobalAPI); out.globalAPI = GlobalAPI
table.sort(LuaAPI); out.luaAPI = LuaAPI
table.sort(FrameXML); out.frameXML = FrameXML
table.sort(Frames); out.frames = Frames
table.sort(Mixins); out.mixins = Mixins
out.templates = {}
for name, t in pairs(Templates) do
  out.templates[name] = { t.type, t.inherits, t.mixin }
end
out.events = {}
for _, list in pairs(Events) do for _, e in ipairs(list) do out.events[#out.events + 1] = e end end
table.sort(out.events)
out.cvars = {}
for name, v in pairs(CVars.var or {}) do out.cvars[name] = v[1] end
out.enums = enumEnv.Enum or {}
out.constants = enumEnv.Constants or {}
out.globals = {}
for k, v in pairs(enumEnv) do
  if k ~= "Enum" and k ~= "Constants" and (type(v) == "number" or type(v) == "string" or type(v) == "boolean") then
    out.globals[k] = v
  end
end

local function ser(v, ind)
  local t = type(v)
  if t == "string" then return string.format("%q", v) end
  if t == "number" then
    if v == math.floor(v) and math.abs(v) < 2^53 then return string.format("%d", v) end
    return string.format("%.17g", v)
  end
  if t ~= "table" then return tostring(v) end
  local n = #v
  local parts = {}
  for i = 1, n do parts[#parts + 1] = ser(v[i], ind) end
  local keys = {}
  for k in pairs(v) do if not (type(k) == "number" and k >= 1 and k <= n and k == math.floor(k)) then keys[#keys + 1] = k end end
  table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
  for _, k in ipairs(keys) do
    local ks = (type(k) == "string" and k:match("^[%a_][%w_]*$")) and k or ("[" .. ser(k) .. "]")
    parts[#parts + 1] = ks .. "=" .. ser(v[k], ind)
  end
  if ind and ind < 2 then
    local pad = string.rep(" ", ind + 1)
    return "{\n" .. pad .. table.concat(parts, ",\n" .. pad) .. "\n" .. string.rep(" ", ind) .. "}"
  end
  return "{" .. table.concat(parts, ",") .. "}"
end

io.write("-- GENERATED by tools/gen-resources.lua from Ketho/BlizzardInterfaceResources. Do not edit.\n")
io.write("-- Source: " .. source .. "\n")
io.write(string.format("-- %d global API, %d FrameXML functions, %d frames, %d templates, %d events, %d CVars\n",
  #out.globalAPI, #out.frameXML, #out.frames, (function() local n = 0 for _ in pairs(out.templates) do n = n + 1 end return n end)(),
  #out.events, (function() local n = 0 for _ in pairs(out.cvars) do n = n + 1 end return n end)()))
io.write("return " .. ser(out, 0) .. "\n")
