-- Writes addons/SimCheck/Data.lua: the events and CVars the simulator knows,
-- so the SimCheck addon can ask the real client about each one.
--   lua5.1 tools/gen-simcheck-data.lua > addons/SimCheck/Data.lua
package.path = "./?.lua;./?/init.lua;" .. package.path
local apidocs = require("wowapi.data.apidocs")
local res = require("wowapi.resources").data()

local function sorted(set)
  local out = {}
  for k in pairs(set) do out[#out + 1] = k end
  table.sort(out)
  return out
end

local events = {}
for name in pairs(apidocs.events) do events[name] = true end
for _, name in ipairs(res.events) do events[name] = true end
-- events addons register that newer clients removed
for _, name in ipairs({ "UNIT_HEALTH_FREQUENT", "COMBAT_LOG_EVENT_UNFILTERED", "UNIT_COMBAT", "CHAT_MSG_COMBAT_XP_GAIN",
  "UNIT_SPELLCAST_CHANNEL_UPDATE", "PLAYER_TALENT_UPDATE", "ACTIVE_TALENT_GROUP_CHANGED", "CHARACTER_POINTS_CHANGED",
  "UNIT_POWER_FREQUENT", "BAG_UPDATE_DELAYED", "ITEM_LOCK_CHANGED", "COMPANION_UPDATE", "ENCOUNTER_START" }) do
  events[name] = true
end

local function list(name, items)
  local out = { "ns." .. name .. " = {" }
  local line = " "
  for _, v in ipairs(items) do
    local piece = string.format(" %q,", v)
    if #line + #piece > 118 then out[#out + 1] = line; line = " " end
    line = line .. piece
  end
  if line ~= " " then out[#out + 1] = line end
  out[#out + 1] = "}"
  return table.concat(out, "\n")
end

io.write("-- Generated by tools/gen-simcheck-data.lua from the simulator's API data. Don't edit.\n")
io.write("local _, ns = ...\n\n")
io.write(list("EVENTS", sorted(events)), "\n\n")
io.write(list("CVARS", sorted(res.cvars)), "\n")
