-- Extracts constant values (numbers, strings, booleans and simple tables of
-- them) that Blizzard's FrameXML defines in Lua, by executing the given
-- files in a sandbox. Functions and anything depending on the game are
-- skipped. Output: wowapi/data/constants.lua
--
--   lua5.1 tools/gen-constants.lua "<source>" file1.lua file2.lua ... > wowapi/data/constants.lua
local source = table.remove(arg, 1)
local dummy
local function ret() return dummy end
dummy = setmetatable({}, { __index = ret, __call = ret, __add = ret, __sub = ret, __mul = ret, __div = ret,
  __unm = ret, __mod = ret, __concat = ret, __newindex = function() end })

local env = setmetatable({}, { __index = function(_, k)
  local v = _G[k]
  if v ~= nil and (k == "math" or k == "string" or k == "table" or k == "pairs" or k == "ipairs" or k == "type"
    or k == "tostring" or k == "tonumber" or k == "select" or k == "unpack" or k == "floor") then return v end
  return dummy
end })
env.Enum = dummy
env.Constants = dummy

for _, file in ipairs(arg) do
  local f = io.open(file, "rb")
  local src = f and f:read("*a") or ""
  if f then f:close() end
  src = src:gsub("^\239\187\191", "")
  local chunk, lerr = loadstring(src, "@" .. file)
  if not chunk then io.stderr:write(file .. ": " .. tostring(lerr) .. "\n") end
  if chunk then
    setfenv(chunk, env)
    local ok, err = pcall(chunk)
    if not ok then io.stderr:write(file .. ": stopped at: " .. tostring(err) .. "\n") end
  end
end

local function simple(v, depth)
  local t = type(v)
  if t == "number" or t == "string" or t == "boolean" then return true end
  if t ~= "table" or v == dummy or depth > 2 then return false end
  if getmetatable(v) then return false end
  for k, x in pairs(v) do
    if (type(k) ~= "string" and type(k) ~= "number") or not simple(x, depth + 1) then return false end
  end
  return next(v) ~= nil
end

local function ser(v)
  local t = type(v)
  if t == "string" then return string.format("%q", v) end
  if t == "number" then
    if v ~= v or v == math.huge or v == -math.huge then return "0" end
    if v == math.floor(v) and math.abs(v) < 2^53 then return string.format("%d", v) end
    return string.format("%.17g", v)
  end
  if t ~= "table" then return tostring(v) end
  local keys = {}
  for k in pairs(v) do keys[#keys + 1] = k end
  table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
  local parts = {}
  for _, k in ipairs(keys) do
    local ks = (type(k) == "string" and k:match("^[%a_][%w_]*$")) and k or ("[" .. ser(k) .. "]")
    parts[#parts + 1] = ks .. "=" .. ser(v[k])
  end
  return "{" .. table.concat(parts, ",") .. "}"
end

local names = {}
for k, v in pairs(env) do
  if type(k) == "string" and k ~= "Enum" and k ~= "Constants" and simple(v, 0) then names[#names + 1] = k end
end
table.sort(names)
io.write("-- GENERATED by tools/gen-constants.lua from Blizzard FrameXML constants. Do not edit.\n")
io.write("-- Source: " .. source .. "\n")
io.write("return {\n")
for _, k in ipairs(names) do io.write(" ", k, "=", ser(env[k]), ",\n") end
io.write("}\n")
io.stderr:write(#names .. " constants\n")
